name: Deploy static site with optimized assets

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install CLI tools
        run: |
          npm install -g clean-css-cli terser

      - name: Install WebP tools
        run: |
          sudo apt-get update
          sudo apt-get install -y webp

      - name: Prepare dist folder
        run: |
          mkdir -p dist/assets
          cp index.html dist/
          cp -r images dist/images
          cp -r css/styles.css dist/assets/
          cp -r css/fonts dist/assets/fonts
          cp -r js/*.js dist/assets/

      - name: Convert images to WebP
        run: |
          mkdir -p dist/images
          cwebp -resize 1905 886 -q 80 images/Hero_Desktop.jpg -o dist/images/Hero_Desktop.webp
          cwebp -resize 934 749 -q 80 images/Hero_Tablet.jpg -o dist/images/Hero_Tablet.webp
          cwebp -resize 618 618 -q 80 images/Hero_Mobile.jpg -o dist/images/Hero_Mobile.webp
          cwebp -resize 200 200 -q 80 images/vr1.jpg -o dist/images/vr1.webp
          cwebp -resize 200 200 -q 80 images/vr2.jpg -o dist/images/vr2.webp
          cwebp -resize 200 200 -q 80 images/vr3.jpg -o dist/images/vr3.webp
          cwebp -resize 36 26 -q 80 images/menu_icon.png -o dist/images/menu_icon.webp

      - name: Minify CSS
        run: |
          cleancss -o dist/assets/styles.min.css dist/assets/styles.css
          rm dist/assets/styles.css

      - name: Minify JS
        run: |
          terser dist/assets/main.js -o dist/assets/main.min.js --compress --mangle
          terser dist/assets/products.js -o dist/assets/products.min.js --compress --mangle
          rm dist/assets/main.js dist/assets/products.js

      - name: Update HTML references
        run: |
          sed -i 's/css\/styles\.css/assets\/styles.min.css/g' dist/index.html
          sed -i 's/js\/main\.js/assets\/main.min.js/g' dist/index.html
          sed -i 's/js\/products\.js/assets\/products.min.js/g' dist/index.html
          # sed -i 's/\.\(png\|jpg\|jpeg\)/.webp/g' dist/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
